In [6]:
import numpy as np
import pandas as pd

npz_path = "Data/output_displacement/barbell_biceps_curl/training_data_displacement.npz"
data = np.load(npz_path, allow_pickle=True)

data.files  # see available arrays/keys

['X',
 'y',
 'y_class',
 'y_class_onehot',
 'y_class_raw',
 'class_names',
 'n_landmarks']

In [ ]:
X = data["X"]          # (N, T*12*3 + class_dim)
y = data["y"]          # (N, T*12*3)
y_class = data["y_class"]
class_names = data["class_names"]

dfX = pd.DataFrame(X)
dfy = pd.DataFrame(y)

display(dfX.head())
display(dfy.head())

,0,1,2,3,4,5,6,7,8,9,...,531,532,533,534,535,536,537,538,539,540
0,0.513579,0.210269,0.037210,0.416907,0.211962,-0.086784,0.514400,0.345949,0.057903,0.409477,...,0.404580,0.699649,-0.049423,0.549285,0.885780,0.164506,0.367552,0.902325,0.069952,1.0
1,0.513145,0.211962,-0.086784,0.416474,0.210269,0.037210,0.520576,0.353025,-0.119482,0.415653,...,0.411097,0.696834,0.026353,0.564334,0.902325,0.069952,0.382600,0.885780,0.164506,1.0
2,0.513537,0.211567,0.074483,0.415735,0.212297,-0.035239,0.514879,0.347732,0.052393,0.411423,...,0.336182,0.743368,-0.145147,0.549300,0.884997,0.159987,0.367532,0.902320,0.070882,1.0
3,0.515624,0.212297,-0.035239,0.417823,0.211567,0.074483,0.519936,0.348877,-0.121674,0.416480,...,0.447360,0.644756,0.037337,0.563554,0.902320,0.070882,0.394354,0.941283,0.106859,1.0
4,0.513754,0.214161,0.069735,0.414839,0.212295,-0.018701,0.512289,0.366182,0.006324,0.414553,...,0.405041,0.698230,-0.043366,0.549325,0.884958,0.158663,0.367552,0.902375,0.061219,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2859,0.573056,0.357822,0.035443,0.425341,0.348054,-0.215061,0.588639,0.552260,0.128093,0.418468,...,0.495424,1.241027,0.103826,0.596407,1.518519,0.201026,0.501037,1.514464,0.494804,1.0
2860,0.609859,0.359421,-0.276839,0.447721,0.357065,0.010811,0.623229,0.623756,-0.306724,0.443416,...,0.462133,1.151819,0.149950,0.588911,1.636722,0.272758,0.475311,1.600773,0.334973,1.0
2861,0.605969,0.357065,0.010811,0.443831,0.359421,-0.276839,0.610274,0.564230,0.124578,0.430461,...,0.497176,1.291781,0.028765,0.609849,1.600773,0.334973,0.496249,1.636722,0.272758,1.0
2862,0.645413,0.367359,-0.256346,0.487207,0.364207,0.062837,0.658495,0.619816,-0.343299,0.458635,...,0.496641,1.218119,0.138686,0.589267,1.570140,0.227400,0.475311,1.600773,0.334973,1.0
2863,0.596512,0.364207,0.062837,0.438306,0.367359,-0.256346,0.625084,0.568609,0.181285,0.425224,...,0.489621,1.288891,0.111979,0.609849,1.600773,0.334973,0.538453,1.627594,0.283534,1.0

,0,1,2,3,4,5,6,7,8,9,...,26,27,28,29,30,31,32,33,34,35
0,-0.0,-0.0,-0.0,-0.000000,-0.00000,-0.000000,-0.087753,-0.089997,0.079717,-0.070894,...,0.023249,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
1,-0.0,-0.0,-0.0,-0.000000,-0.00000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,...,0.063803,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
2,-0.0,-0.0,-0.0,-0.000000,-0.00000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,...,-0.000000,0.068814,-0.044895,0.097536,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
3,-0.0,-0.0,-0.0,-0.000000,-0.00000,-0.000000,-0.000000,-0.000000,-0.000000,0.048693,...,-0.000000,-0.036972,0.051219,-0.017801,-0.000000,-0.000000,-0.000000,-0.012567,-0.056286,0.053128
4,-0.0,-0.0,-0.0,0.027084,0.09035,0.021052,-0.000000,-0.000000,-0.000000,-0.000000,...,-0.007424,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2859,-0.0,-0.0,-0.0,-0.000000,-0.00000,-0.000000,0.024433,-0.073376,-0.005618,-0.000000,...,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
2860,-0.0,-0.0,-0.0,-0.000000,-0.00000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,...,-0.000000,0.034509,0.066299,-0.011264,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
2861,-0.0,-0.0,-0.0,-0.000000,-0.00000,-0.000000,-0.049772,-0.009450,0.068056,-0.000000,...,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
2862,-0.0,-0.0,-0.0,-0.000000,-0.00000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,...,0.005999,-0.000000,-0.000000,-0.000000,-0.000356,0.066582,0.045358,-0.000000,-0.000000,-0.000000
2863,-0.0,-0.0,-0.0,-0.000000,-0.00000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,...,-0.000000,0.007555,0.002890,-0.083214,-0.000000,-0.000000,-0.000000,-0.042204,0.009128,-0.010776