In [1]:
import numpy as np
import pandas as pd

npz_path = "Data/output_displacement_single_frame_new/bicep_curls/training_data_displacement_per_frame.npz"
data = np.load(npz_path, allow_pickle=True)

data.files  # see available arrays/keys

['X',
 'y',
 'y_class',
 'y_class_onehot',
 'y_class_raw',
 'class_names',
 'n_landmarks',
 'n_coords',
 'sequence_length']

In [2]:
X = data["X"]          # (N, T*12*3 + class_dim)
print(X.shape)
y = data["y"]          # (N, T*12*3)
y_class = data["y_class"]
class_names = data["class_names"]

dfX = pd.DataFrame(X)
dfy = pd.DataFrame(y)

display(dfX.head())
dfy

(42021, 25)

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
0,0.513579,0.210269,0.416907,0.211962,0.514400,0.345949,0.409477,0.353025,0.535368,0.445047,...,0.486656,0.488499,0.717178,0.403348,0.702650,0.482560,0.840676,0.367726,0.901125,1.0
1,0.454920,0.178195,0.416770,0.211956,0.514485,0.347260,0.410158,0.353266,0.535384,0.445035,...,0.486892,0.520102,0.696695,0.403272,0.704244,0.548373,0.885276,0.367733,0.901464,1.0
2,0.513660,0.210491,0.416643,0.211960,0.514549,0.347775,0.323389,0.265740,0.535396,0.444990,...,0.486986,0.520342,0.698317,0.403304,0.704248,0.548508,0.885399,0.367728,0.901481,1.0
3,0.513686,0.210723,0.416571,0.211992,0.567267,0.397090,0.410826,0.353436,0.535615,0.445842,...,0.486965,0.520579,0.699001,0.403284,0.704623,0.548665,0.885419,0.367711,0.901833,1.0
4,0.567311,0.292535,0.416442,0.212027,0.514727,0.348269,0.411078,0.353513,0.535785,0.445778,...,0.486967,0.520752,0.700046,0.403205,0.704916,0.548849,0.885499,0.360034,0.904420,1.0

,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
0,-0.000000,-0.000000,-0.0,-0.0,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,...,-0.0,-0.0,0.031202,-0.023997,-0.000000,-0.000000,0.065613,0.044534,-0.000000,-0.000000
1,0.058702,0.032165,-0.0,-0.0,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,...,-0.0,-0.0,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
2,-0.000000,-0.000000,-0.0,-0.0,-0.000000,-0.000000,0.087052,0.087587,-0.000000,-0.000000,...,-0.0,-0.0,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
3,-0.000000,-0.000000,-0.0,-0.0,-0.052604,-0.048947,-0.000000,-0.000000,-0.000000,-0.000000,...,-0.0,-0.0,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
4,-0.053625,-0.081799,-0.0,-0.0,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,...,-0.0,-0.0,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,0.007677,-0.002511
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42016,-0.000000,-0.000000,-0.0,-0.0,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,...,-0.0,-0.0,-0.047349,0.003615,-0.000000,-0.000000,-0.000000,-0.000000,0.097936,-0.079387
42017,-0.000000,-0.000000,-0.0,-0.0,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,...,-0.0,-0.0,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.048572,0.020410
42018,-0.000000,-0.000000,-0.0,-0.0,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,...,-0.0,-0.0,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
42019,-0.000000,-0.000000,-0.0,-0.0,-0.000000,-0.000000,-0.023803,-0.085887,-0.000000,-0.000000,...,-0.0,-0.0,-0.000000,-0.000000,0.027223,0.010354,-0.000000,-0.000000,-0.000000,-0.000000
42020,-0.053917,0.083418,-0.0,-0.0,-0.000000,-0.000000,-0.000000,-0.000000,-0.032281,-0.052543,...,-0.0,-0.0,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000